FROM maven:3.8.4-eclipse-temurin-17 as builder

ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME

COPY settings.xml /usr/share/maven

ARG GITHUB_TOKEN
ENV MAVEN_REPO_TOKEN=$GITHUB_TOKEN

ARG GITHUB_USER
ENV MAVEN_REPO_USER=$GITHUB_USER

COPY pom.xml .
RUN mvn dependency:go-offline -B -s /usr/share/maven/settings.xml

COPY . $HOME 
ENV PROFILE=dev
# RUN --mount=type=cache,target=/home/adnan/.m2 mvn -f $HOME/pom.xml clean install -s $HOME/settings.xml
RUN mvn package spring-boot:repackage -s $HOME/settings.xml

FROM eclipse-temurin:17-jre-alpine 
RUN rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Dhaka /etc/localtime \
&& echo "Asia/Dhaka" > /etc/timezone

WORKDIR /opt/app

ENV CONFIG_URI=configserver:http://192.168.1.82:30010/
ARG ENC_PASSWORD
ENV ENC_PASSWORD=$ENC_PASSWORD
ENV ACTIVE_PROFILE=dev

EXPOSE 7770

COPY --from=builder /usr/app/target/*.jar /opt/app/ec-core-service-0.0.1.jar

ENTRYPOINT ["java", "-jar", "/opt/app/ec-core-service-0.0.1.jar" ]
